Models/Item.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OddballStore.Models
{
    public class Item
    {
        public int ItemID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Price { get; set; }
        public string Thumbnail { get; set; }

        public Item() { }

        public Item(string name, string description, int price, string thumbnail)
        {
            Name = name;
            Description = description;
            Price = price;
            Thumbnail = thumbnail;
        }

        public Item(int itemID, string name, string description, int price, string thumbnail)
        {
            ItemID = itemID;
            Name = name;
            Description = description;
            Price = price;
            Thumbnail = thumbnail;
        }
    }
    
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Session;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using OddballStore.Data;
using OddballStore.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using System.Text.Json;

namespace OddballStore.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _context;

        public HomeController(ILogger<HomeController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;

        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            return View();
        }

        [Authorize]
        public IActionResult Profile()
        {
            return View();
        }

        [AllowAnonymous]
        public IActionResult Cart()
        {
            var json = HttpContext.Session.GetString("cart");
            List<CartItem> cartList = new List<CartItem>();

            if (json != null)
            {
                cartList = JsonSerializer.Deserialize<List<CartItem>>(json);
            }

            return View(cartList);
        }




        [AllowAnonymous]
        public async Task<IActionResult> Items()
        {
            return View(await _context.Items.ToListAsync());
        }

        [HttpPost]
        public async Task<IActionResult> Items([Bind("ItemID, Name, Description, Price, Thumbnail")] Item item)
        {
            List<CartItem> cartList;

            var json = HttpContext.Session.GetString("cart");
            if (json != null)
            {
                cartList = JsonSerializer.Deserialize<List<CartItem>>(json);
            }
            else
            {
                cartList = new List<CartItem>();
            }

            var itemInCart = false;

            if (cartList.Count > 0)
            {
                for (int i = 0; i < cartList.Count; i++)
                {
                    if (cartList[i].Item.ItemID == item.ItemID)
                    {
                        cartList[i].Quantity += 1;
                        itemInCart = true;
                    }
                }
            }

            if (!itemInCart)
            {
                cartList.Add(new CartItem(item, 1));
            }

            json = JsonSerializer.Serialize(cartList);
            HttpContext.Session.SetString("cart", json);

            return View(await _context.Items.ToListAsync());
        }

        [HttpPost]
        public IActionResult Checkout()
        {

            List<CartItem>  cartList = new List<CartItem>();
            var json = JsonSerializer.Serialize(cartList);
            HttpContext.Session.SetString("cart", json);

            return View("Cart", cartList);
        }

        [HttpPost]
        public IActionResult Quantity(int quantityNum, int itemID)
        {
            var json = HttpContext.Session.GetString("cart");
            List<CartItem> cartList = new List<CartItem>();

            if (json != null)
            {
                cartList = JsonSerializer.Deserialize<List<CartItem>>(json);

                for (int i = 0; i < cartList.Count; i++)
                {
                    if (cartList[i].Item.ItemID == itemID)
                    {
                        cartList[i].Quantity = quantityNum;
                    }
                }

                json = JsonSerializer.Serialize(cartList);
                HttpContext.Session.SetString("cart", json);
            }

            return View("Cart", cartList);
        }

        [HttpPost]
        public IActionResult Delete(int itemID)
        {
            var json = HttpContext.Session.GetString("cart");
            List<CartItem> cartList = new List<CartItem>();

            if (json != null)
            {
                cartList = JsonSerializer.Deserialize<List<CartItem>>(json);

                for (int i = 0; i < cartList.Count; i++)
                {
                    if (cartList[i].Item.ItemID == itemID)
                    {
                        cartList.RemoveAt(i);
                    }
                }

                json = JsonSerializer.Serialize(cartList);
                HttpContext.Session.SetString("cart", json);
            }

            return View("Cart", cartList);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OddballStore.Data;
using OddballStore.Models;

namespace OddballStore.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ItemController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ItemController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Item
        public async Task<IActionResult> Index()
        {
            return View(await _context.Items.ToListAsync());
        }

        // GET: Item/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Items
                .FirstOrDefaultAsync(m => m.ItemID == id);
            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        // GET: Item/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Item/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ItemID,Name,Description,Price,Thumbnail")] Item item)
        {
            if (ModelState.IsValid)
            {
                _context.Add(item);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(item);
        }

        // GET: Item/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Items.FindAsync(id);
            if (item == null)
            {
                return NotFound();
            }
            return View(item);
        }

        // POST: Item/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ItemID,Name,Description,Price,Thumbnail")] Item item)
        {
            if (id != item.ItemID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(item);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ItemExists(item.ItemID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(item);
        }

        // GET: Item/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Items
                .FirstOrDefaultAsync(m => m.ItemID == id);
            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        // POST: Item/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var item = await _context.Items.FindAsync(id);
            _context.Items.Remove(item);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ItemExists(int id)
        {
            return _context.Items.Any(e => e.ItemID == id);
        }
    }
}

Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using OddballStore.Data;
using OddballStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OddballStore.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserController : Controller
    {
        private readonly ILogger<UserController> _logger;
        private readonly ApplicationDbContext _context;

        public UserController(ILogger<UserController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public ActionResult AllUsers()
        {
            return View(_context.Users.ToList());
        }

        //GET: Home/EditUser/s
        [HttpGet]
        public async Task<IActionResult> EditUser(string? id)
        {
            if (id == null)
            {
                return View("AllUsers", _context.Users.ToList());
            }

            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                //go to different view
                return View("AllUsers", _context.Users.ToList());
            }
            return View(user);
        }

        [HttpPost]
        public async Task<IActionResult> EditUser(string email, [Bind("Id, Email, PhoneNumber")] User user)
        {
            var saved = false;

            user.UserName = email;

            while (!saved)
            {
                try
                {
                    // Attempt to save changes to the database
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                    saved = true;
                }
                catch (DbUpdateConcurrencyException ex)
                {
                    foreach (var entry in ex.Entries)
                    {
                        if (entry.Entity is User)
                        {
                            var proposedValues = entry.CurrentValues;
                            var databaseValues = entry.GetDatabaseValues();

                            foreach (var property in proposedValues.Properties)
                            {
                                var proposedValue = proposedValues[property];
                                var databaseValue = databaseValues[property];

                                // TODO: decide which value should be written to database
                                proposedValues[property] = proposedValue;
                            }

                            // Refresh original values to bypass next concurrency check
                            entry.OriginalValues.SetValues(databaseValues);
                        }
                        else
                        {
                            throw new NotSupportedException(
                                "Don't know how to handle concurrency conflicts for "
                                + entry.Metadata.Name);
                        }
                    }
                }
            }
            return View("AllUsers", _context.Users.ToList());
        }

        [HttpPost]
        public async Task<IActionResult> DeleteUser(string? id)
        {

            if (id == null)
            {
                return View("AllUsers", _context.Users.ToList());
            }
            var user = await _context.Users.FindAsync(id);

            if (user == null)
            {
                //go to different view
                return View("AllUsers", _context.Users.ToList());
            }

            _context.Users.Remove(user);
            await _context.SaveChangesAsync();

            return View("AllUsers", _context.Users.ToList());
        }

        [HttpGet]
        public IActionResult CreateUser()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateUser([Bind("Email, Password, PhoneNumber")] User user)
        {

            return View();
        }

        private bool UserExists(string id) => _context.Users.Any(e => e.Id == id);
    }
}

Views/Home/Cart.cshtml
@model List<CartItem>;
@{
    ViewData["Title"] = "Cart";

    int subtotal = 0;
    double taxAmount = 0;
    double total = 0;

    for (int i = 0; i < Model.Count; i++)
    {
        subtotal += Model[i].Item.Price * Model[i].Quantity;
    }

    taxAmount = subtotal * 0.1;
    total = subtotal + taxAmount;
}

<div class="text-center">
    <h1 class="display-4">Cart</h1>
</div>
<div class="container-fluid">
    <div class="row">
        @foreach (var cartItem in Model)
        {
            <div class="divBackground col-lg-3 d-flex flex-column text-center shadow-sm p-4 mb-4" height="700px">
                <img src="~/images/@Html.DisplayFor(modelItem => cartItem.Item.Thumbnail)" class="img-thumbnail mx-auto" height="75" width="75" /><br />
                Name:<br />
                @Html.DisplayFor(modelItem => cartItem.Item.Name)<br /><br />
                Description:<br />
                @Html.DisplayFor(modelItem => cartItem.Item.Description)<br /><br />
                Price:<br />
                @Html.DisplayFor(modelItem => cartItem.Item.Price) gp<br /><br />
                <div class="mx-auto align-self-end">
                    <form method="POST" asp-action="Quantity">
                        <input type="number" id="quantityNum" name="quantityNum" value="@Html.DisplayFor(modelItem => cartItem.Quantity)" class="text-center" />
                        <input type="hidden" id="itemId" name="itemId" value="@cartItem.Item.ItemID">
                        <input type="submit" value="Update" class="btn-block" />
                    </form>
                    <br />
                    <form method="POST" asp-action="Delete">
                        <input type="hidden" id="itemId" name="itemId" value="@cartItem.Item.ItemID">
                        <input type="submit" value="Delete" class="btn-block" />
                    </form>
                </div>
            </div>
        }
    </div>
</div>
<br />
<br />

<div class="divBackground2 padding" height="700px">
    Subtotal: @subtotal gp<br />
    Tax: @taxAmount gp<br />
    Total: @total gp<br /><br />
    <form method="Post" class="alignRight" asp-action="Checkout">
        <input type="submit" value="Checkout" class="btn-block" />
    </form>
</div>

Views/Home/Index.cshtml
@model OddballStore.Models.User
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome To Oddball’s Oddities</h1>
</div>
<div>
    <br />
    <br />
    <p>Default page nothing here. Look Away!!</p>

</div>

Views/Home/Items.cshtml
@model IEnumerable<OddballStore.Models.Item>

@{
    ViewData["Title"] = "Items";
}

<div class="text-center">
    <h1 class="display-4">Store</h1>
</div>
<div class="container-fluid">
    <div class="row">
       @foreach (var item in Model)
        {
            <div class="divBackground col-lg-3 d-flex flex-column text-center shadow-sm p-4 mb-4" height="700px">
                <img src="~/images/@Html.DisplayFor(modelItem => item.Thumbnail)" class="img-thumbnail mx-auto" height="75" width="75" /><br />
                Name:<br />
                @Html.DisplayFor(modelItem => item.Name)<br /><br />
                Description:<br />
                @Html.DisplayFor(modelItem => item.Description)<br /><br />
                Price:<br />
                @Html.DisplayFor(modelItem => item.Price) gp<br /><br />
                <div class="mx-auto align-self-end">
                    <form method="post" asp-area="" asp-controller="Home" asp-action="Items">
                        <input type="hidden" id="ItemId" name="ItemId" value="@item.ItemID">
                        <input type="hidden" id="Name" name="Name" value="@item.Name">
                        <input type="hidden" id="Description" name="Description" value="@item.Description">
                        <input type="hidden" id="Price" name="Price" value="@item.Price">
                        <input type="hidden" id="Thumbnail" name="Thumbnail" value="@item.Thumbnail">
                        <input type="submit" value="Add to Cart" class="btn-block" />
                    </form>
                </div>
            </div>
        }
    </div>
</div>

Views/Home/Profile.cshtml
@model OddballStore.Models.User
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

@{
    ViewData["Title"] = "Profile";
}

@if (SignInManager.IsSignedIn(User))
{

    IdentityUser currentUser = await UserManager.GetUserAsync(User);

    <h1 class="display-1">Profile</h1>

    <div class="jumbotron">
        <h3 class="display-4">Edit User Information</h3>
        <form asp-controller="HomeController" asp-action="UpdateProfile" method="post">
            <div class="form-group">
                <label asp-for="Email">Email: </label>
                <input type="text" value="@currentUser.Email" class="form-control" disabled/>
            </div>

            <div class="form-group">
                <label asp-for="PhoneNumber">Phone: </label>
                <input type="text" value="@currentUser.PhoneNumber" class="form-control" disabled />
            </div>

        </form>
    </div>

    var userRoles = await UserManager.GetRolesAsync(currentUser);

    if (userRoles.Contains("Admin"))
    {
        <div class="jumbotron">
            <h3 class="display-4">Admin</h3>
            <form asp-area="" asp-controller="Item" asp-action="Index" method="post">
                <div class="form-group">
                    <input type="submit" value="Edit Store Items"  class="btn btn-outline-dark" />
                    
                </div>
            </form>

            <form asp-area="" asp-controller="User" asp-action="AllUsers" method="post">
                <input type="submit" value="Edit User List" class="btn btn-outline-dark" />
            </form>
        </div>
    }


}
else
{

    <p>Begone</p>
}